#!/bin/bash
# tmux requires unrecognized OSC sequences to be wrapped with DCS tmux;
# <sequence> ST, and for all ESCs in <sequence> to be replaced with ESC ESC. It
# only accepts ESC backslash for ST.
function print_osc() {
    if [ x"$TERM" = "xscreen" ] ; then
        printf "\033Ptmux;\033\033]"
    else
        printf "\033]"
    fi
}

# More of the tmux workaround described above.
function print_st() {
    if [ x"$TERM" = "xscreen" ] ; then
        printf "\a\033\\"
    else
        printf "\a"
    fi
}

function list_file() {
  direct=$1
  sub=$2
  for file in $(ls $direct)
  do
    if [ ! -d $file ]; then
      if [ $sub ]; then
        display_img "$direct/$file"
      else
        display_img "$file"
      fi
    else
      ls -dl "$file"
    fi
  done
}

function display_img() {
  fn=$1
  dims=$(php -r '$a = getimagesize("$argv[1]"); if ($a==FALSE) exit(1); else { echo $a[0] . "x" .$a[1]; exit(0); }' "$fn")
  rc=$?
  if [[ $rc == 0 ]] ; then
    print_osc
    printf '1337;File=name='`echo -n "$fn" | base64`";"
    wc -c "$fn" | awk '{printf "size=%d",$1}'
    printf ";inline=1;height=3;width=3;preserveAspectRatio=true"
    printf ":"
    base64 < "$fn"
    print_st
    if [ x"$TERM" == "xscreen" ] ; then
      printf '\033[4C\033[Bx'
    else
      printf '\033[A'
    fi
    echo -n "$dims "
    ls -l "$fn"
  else
    ls -l "$fn"
  fi
}

if [ $# -eq 0 ]; then
  list_file "./"
else
  for fn in "$@"
  do
    if [ ! -d $fn ]; then
      list_file "$fn"
    else
      list_file "$fn" "sub"
    fi
  done
fi

